### ISSUE TITLE
HUD中饥饿条显示异常

### ISSUE THREAD

**Issue by CrystMaple** [sheep-realms/Perspective-highlight#11]
- [x] 我已确认该资源包的最新版本中依然存在此问题。
- [x] 我已确认该问题发生在受支持的游戏版本中。
- [x] 我已确认近期没有其他人提出类似问题。

## 问题描述
从资源包5.4版本开始，HUD中的饥饿条显示错乱，如饱食度满时十个鸡腿图标均显示为半个鸡腿等。

## 截图
![p1](https://github.com/sheep-realms/Perspective-highlight/assets/146744800/22639496-0853-498b-8bd5-e5a34d6940a3)
![p2](https://github.com/sheep-realms/Perspective-highlight/assets/146744800/9948a2ba-4af4-4149-9776-1c3949cd4fa2)
![p3](https://github.com/sheep-realms/Perspective-highlight/assets/146744800/d6ab3975-6070-4905-aa1e-44148193a53d)

以下为未启用资源包时的饥饿条：
![p4](https://github.com/sheep-realms/Perspective-highlight/assets/146744800/3efb4d85-9864-4008-9535-fa0e730fd200)

## 解决方案
可能与5.4中GUI贴图格式调整有关

## 环境信息
资源包版本：5.4

游戏版本：1.20.2

其他画面优化Mod（若有）：Sodium，但去除Sodium后仍有此特性

**Comment by MC-luoluo** [comment]
这个问题影响挺严重的……应该为修复这个（单独）发一个更新版本吧

**Comment by sheep-realms** [comment]
初步判定为自动化切图工具配置出错，正在处理

**Comment by sheep-realms** [comment]
已于 5.5 版本修复
