### ISSUE TITLE
游戏内显示资源包版本与文件命名不符

### ISSUE THREAD

**Issue by MC-luoluo** [sheep-realms/Perspective-highlight#12]
- [x] 我已确认该资源包的最新版本中依然存在此问题。
- [x] 我已确认该问题发生在受支持的游戏版本中。
- [x] 我已确认近期没有其他人提出类似问题。

## 问题描述
游戏中显示版本为v5.4，但该文件名为v5.5

## 期望效果
游戏中版本与文件名匹配

## 截图
![图片](https://github.com/sheep-realms/Perspective-highlight/assets/113677351/7ba694ac-4a8d-4eae-8a85-099bed2edfda)

## 解决方案
修改pack.mcmeta文件中的资源包介绍

## 环境信息
v5.5

## 其他
baka！

**Comment by sheep-realms** [comment]
不修了，等下个版本，又不是不能用.jpg
