### ISSUE TITLE
资源包5.1版本下界疣侧面纹理丢失

### ISSUE THREAD

**Issue by erythritols** [sheep-realms/Perspective-highlight#3]
- [x] 我已确认该资源包的最新版本中依然存在此问题。
- [x] 我已确认该问题发生在受支持的游戏版本中。
- [x] 我已确认近期没有其他人提出类似问题。

## 问题描述
在 Minecraft 1.19.3和资源包 v5.1中，第二、三、四生长阶段的下界疣侧面显示为丢失的纹理。

## 期望效果
如上

## 截图
![图片](https://user-images.githubusercontent.com/96780976/208456755-ab0a2a8c-9ccf-4448-852f-50d7f36fd57f.png)

## 解决方案
如果您知道如何解决...

## 环境信息
资源包版本：5.1

游戏版本：1.19.3

**Comment by sheep-realms** [comment]
未发现问题，请再次确认安装了5.1版本的资源包，并且已解压资源包。以防万一，网盘已重新上传5.1版本。如果问题依旧存在，请列出所使用的模组。

**Comment by sheep-realms** [comment]
**特别提醒：不要使用旧版或不稳定的OptiFine，1.19.3有一个重大资源包结构更新，使用旧版OptiFine无法适配1.19.3的新资源包结构。**

**Comment by erythritols** [comment]
大致测试环境：MC1.19.3，Fabric Loader，Sodium，模组均为适用于1.19.3的最新版。
经测试，无模组的Minecraft1.19.3加装资源包后显示正常，一旦安装Iris即会显示异常。另外，此问题与光影包无关（只安装Iris不加载光影包亦异常）。如果使用MC1.19.2和资源包5.0，加装Iris，则无异常，问题仍为最新版资源包与最新版Iris冲突所致。
Iris为Fabirc+Sodium环境下十分常用和必不可少的光影加载工具，前面的版本中二者并无冲突。如果问题并非为Iris单方面漏洞所致，还望制作组能修复。
谢谢！

**Comment by sheep-realms** [comment]
该问题并非资源包本身问题且无法修复，请将此问题反馈给相关模组的开发者。
