### ISSUE TITLE
建议下载地址不要只提供百度网盘

### ISSUE THREAD

**Issue by ghost** [sheep-realms/Perspective-highlight#5]
- [x] 我已确认该资源包近期没有类似更新。
- [x] 我已确认近期没有其他人提出类似提议。

## 提议描述
请在此描述您的提议...
这里已经列出了您可能需要用到的段落结构，请按实际需求删改。

p.s.:两个回车换行

## 实现方法
如果您知道如何实现...

**Comment by sheep-realms** [comment]
暂不支持提供其他下载渠道

**Comment by MC-luoluo** [comment]
百度网盘下载会强制用户登录，建议将资源包上传到modrinth和curseforge，这样做整合包时只需要加一个下载链接，可以压缩整合包打包体积，下载也更加方便

**Comment by sheep-realms** [comment]
封装进整合包会带来很多麻烦，且现阶段不支持多语种适配，不会考虑这些平台。

**Comment by sheep-realms** [comment]
> 百度网盘下载会强制用户登录，建议将资源包上传到modrinth和curseforge，这样做整合包时只需要加一个下载链接，可以压缩整合包打包体积，下载也更加方便

封装进整合包会带来很多麻烦，且现阶段不支持多语种适配，不会考虑这些平台。

**Comment by MC-luoluo** [comment]
> > 百度网盘下载会强制用户登录，建议将资源包上传到modrinth和curseforge，这样做整合包时只需要加一个下载链接，可以压缩整合包打包体积，下载也更加方便
> 
> 封装进整合包会带来很多麻烦，且现阶段不支持多语种适配，不会考虑这些平台。

我的意思是 这样别人做整合包时想把这个资源包放进整合包里只需要在整合包索引文件里加上modrinth/curseforge链接，不用直接把资源包装进整合包里，会方便很多（整合包体积也会小很多）

**Comment by sheep-realms** [comment]
> > > 百度网盘下载会强制用户登录，建议将资源包上传到modrinth和curseforge，这样做整合包时只需要加一个下载链接，可以压缩整合包打包体积，下载也更加方便
> > 
> > 
> > 封装进整合包会带来很多麻烦，且现阶段不支持多语种适配，不会考虑这些平台。
> 
> 我的意思是 这样别人做整合包时想把这个资源包放进整合包里只需要在整合包索引文件里加上modrinth/curseforge链接，不用直接把资源包装进整合包里，会方便很多（整合包体积也会小很多）

无论是直接封装还是链接封装都会给我造成麻烦，请不要安装进任何整合包中。

**Comment by MC-luoluo** [comment]
MCBBS由于一些原因关站维护，是否能考虑在其他平台（比如modrinth和curseforge）发布以便大家下载？

**Comment by sheep-realms** [comment]
> MCBBS由于一些原因关站维护，是否能考虑在其他平台（比如modrinth和curseforge）发布以便大家下载？

不会考虑在其他平台上发布

**Comment by MC-luoluo** [comment]
> > MCBBS由于一些原因关站维护，是否能考虑在其他平台（比如modrinth和curseforge）发布以便大家下载？
> 
> 不会考虑在其他平台上发布

MCBBS已宣布永久关闭，请务必考虑在其他平台发布

**Comment by sheep-realms** [comment]
本资源包宣布停止维护。
