### ISSUE TITLE
请添加1.20和1.20.1支持!

### ISSUE THREAD

**Issue by MC-luoluo** [sheep-realms/Perspective-highlight#6]
- [x] 我已确认该资源包近期没有类似更新。
- [x] 我已确认近期没有其他人提出类似提议。

## 提议描述
请在此描述您的提议...
这里已经列出了您可能需要用到的段落结构，请按实际需求删改。
1.19.4中下界疣的生长资源出错
请添加1.20及1.20.1的新内容支持

p.s.:两个回车换行

## 实现方法
如果您知道如何实现...

**Comment by sheep-realms** [comment]
#3 请检查你的图像优化模组。

1.20新内容正在准备。
