### ISSUE TITLE
对新内容的建议

### ISSUE THREAD

**Issue by MC-luoluo** [sheep-realms/Perspective-highlight#7]
- [x] 我已确认该资源包近期没有类似更新。
- [x] 我已确认近期没有其他人提出类似提议。

## 提议描述
请在此描述您的提议...
这里已经列出了您可能需要用到的段落结构，请按实际需求删改。

谜之炖菜添加状态效果显示(可通过读取nbt内effect id实现)
烟花添加是否爆炸和飞行时间显示
美西螈桶添加颜色显示(nbt内Variant)
紫水晶母岩高亮
可疑的沙子和沙砾高亮
樱花树与木制类物品支持(门,活板门,压力板,按钮,树叶)

p.s.:两个回车换行

## 实现方法
如果您知道如何实现...

**Comment by sheep-realms** [comment]
根据特定nbt改变纹理是OptiFine的功能，原版不支持此功能，且已有类似资源包实现，目前暂不考虑。

其余内容已在下次更新内容中。
