### ISSUE TITLE
末地传送门框架可以看出朝向

### ISSUE THREAD

**Issue by MC-luoluo** [sheep-realms/Perspective-highlight#8]
- [x] 我已确认该资源包近期没有类似更新。
- [x] 我已确认近期没有其他人提出类似提议。

## 提议描述
请在此描述您的提议...
这里已经列出了您可能需要用到的段落结构，请按实际需求删改。

p.s.:两个回车换行

## 实现方法
如果您知道如何实现...

**Comment by sheep-realms** [comment]
将在下一次更新加入
